#!/usr/bin/perl -w
use strict;
$| = 1;

#       Redistribution and use in source and binary forms, with or without
#       modification, are permitted provided that the following conditions are
#       met:
#       
#       * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#       * Redistributions in binary form must reproduce the above
#         copyright notice, this list of conditions and the following disclaimer
#         in the documentation and/or other materials provided with the
#         distribution.
#       * Neither the name of the  nor the names of its
#         contributors may be used to endorse or promote products derived from
#         this software without specific prior written permission.
#       
#       THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#       "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#       LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#       A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#       OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#       SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#       LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#       DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#       THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#       (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#       OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#	Copyright (C) 2008-2011 Aleksandr Deviatkin aka alid

#
# Формат тарифного расписания счетчика Меркурий-230 в протоколе не описан,
# поэтому здесь только управление флагом автоматического перехода на летнее время
# 2011-09-11 alid
#

use lib "$ENV{MY}/counter";
use Mercury;

my (@args, %opts);
foreach(@ARGV){
   if(/^\-(\S)(.*)/){	$opts{$1} = $2;	} else {	push @args, $_;	}
}
my ($saddr, $passwd, $device, $flag) = (@args);
die "Usage: $0 addr password serial-dev"	unless(defined $saddr && $passwd && $device);
$flag |= 0; $flag = ($flag ? 0:1); $flag = sprintf("%02X", $flag);
my $set = exists $opts{f};
my $verb = exists $opts{v};
my $retries = (exists $opts{r}) ? $opts{r} : 10;

my $addr = sprintf("%x",$saddr);
$passwd=sprintf("%x %x %x %x %x %x", split("",$passwd,6));
print "Addr: [$addr] Pw: [$passwd]\n"	if $verb;

my $level=2;
my $STALL_DEFAULT=10; # how many seconds to wait for new input
my $MAXLENGTH = 255;	# наибольшая длина пакета

my ($status,$cnt,@data);
my $connect = Mercury->new($device,'M230',$addr,$passwd,$level,$retries,$verb);

if($verb) {
	print "Connection testing ... "	if $verb;
	$status = $connect->tst();
	print "$status\n"	if $verb;
	die	"[$addr] Connection failed: [$status]"	unless($status=~/ok/);
}

print "Session opening (level $level) ... "	if $verb;
$status = $connect->sopen();

print "$status\n"	if $verb;
die	"[$addr] Session failed: [$status]"	unless($status=~/ok/);

my $cmd;
# get flag from device
if($verb || !$set) {
	$cmd = '08 09';
	$connect->_send($cmd);
	($status,$cnt,@data) = $connect->_recv();
	die "[$addr] request failed: [$status]"	unless($status=~/ok/);
	print "[$status][$cnt][".join(' ',@data)."]\n"	if $verb;
	print "Automatic select winter/summer time: ".(($data[2] & 0x8)? "0":"1")."\n";
}
if($set) {
	print "Setting summer time detection flag to: $flag\n"	if($verb);
	$cmd = '03 18';
	$connect->_send("$cmd $flag");
	$status = $connect->isok();
	print "$status\n"	if $verb;
	die	"[$addr] Session failed: [$status]"	unless($status=~/ok/);
}
print "Session closing ... "	if $verb;
$status = $connect->sclose();
print "$status\n"	if $verb;
$connect->quit();


