#!/usr/bin/perl

#
#       Copyright (C) 2008-2012 Александр Девяткин, "Зелёная горка"
#
#       Разрешается повторное распространение и использование как в виде исходного
#       кода, так и в двоичной форме, с изменениями или без, при соблюдении следующих
#       условий:
#
#       * При повторном распространении исходного кода должно оставаться указанное
#         выше уведомление об авторском праве, этот список условий и последующий
#         отказ от гарантий.
#       * При повторном распространении двоичного кода должна сохраняться указанная
#         выше информация об авторском праве, этот список условий и последующий отказ
#         от гарантий в документации и/или в других материалах, поставляемых при
#         распространении.
#       * Ни название "Зелёная горка", ни имена ее сотрудников не могут быть
#         использованы в качестве поддержки или продвижения продуктов, основанных
#         на этом ПО без предварительного письменного разрешения.
#
#       ЭТА ПРОГРАММА ПРЕДОСТАВЛЕНА ВЛАДЕЛЬЦАМИ АВТОРСКИХ ПРАВ И/ИЛИ ДРУГИМИ СТОРОНАМИ
#	"КАК ОНА ЕСТЬ" БЕЗ КАКОГО-ЛИБО ВИДА ГАРАНТИЙ, ВЫРАЖЕННЫХ ЯВНО ИЛИ ПОДРАЗУМЕВАЕМЫХ,
#	ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ КОММЕРЧЕСКОЙ ЦЕННОСТИ
#	И ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ, ЕСЛИ НЕ ТРЕБУЕТСЯ
#	СООТВЕТСТВУЮЩИМ ЗАКОНОМ, ИЛИ НЕ УСТАНОВЛЕНО В УСТНОЙ ФОРМЕ, НИ ОДИН ВЛАДЕЛЕЦ
#	АВТОРСКИХ ПРАВ И НИ ОДНО ДРУГОЕ ЛИЦО, КОТОРОЕ МОЖЕТ ИЗМЕНЯТЬ И/ИЛИ ПОВТОРНО
#	РАСПРОСТРАНЯТЬ ПРОГРАММУ, КАК БЫЛО СКАЗАНО ВЫШЕ, НЕ НЕСЁТ ОТВЕТСТВЕННОСТИ,
#	ВКЛЮЧАЯ ЛЮБЫЕ ОБЩИЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ ИЛИ ПОСЛЕДОВАВШИЕ УБЫТКИ,
#	ВСЛЕДСТВИЕ ИСПОЛЬЗОВАНИЯ ИЛИ НЕВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ ПРОГРАММЫ (ВКЛЮЧАЯ,
#	НО НЕ ОГРАНИЧИВАЯСЬ ПОТЕРЕЙ ДАННЫХ, ИЛИ ДАННЫМИ, СТАВШИМИ НЕПРАВИЛЬНЫМИ, ИЛИ
#	ПОТЕРЯМИ ПРИНЕСЕННЫМИ ИЗ-ЗА ВАС ИЛИ ТРЕТЬИХ ЛИЦ, ИЛИ ОТКАЗОМ ПРОГРАММЫ РАБОТАТЬ
#	СОВМЕСТНО С ДРУГИМИ ПРОГРАММАМИ), ДАЖЕ ЕСЛИ ТАКОЙ ВЛАДЕЛЕЦ ИЛИ ДРУГОЕ ЛИЦО БЫЛИ
#	ИЗВЕЩЕНЫ О ВОЗМОЖНОСТИ ТАКИХ УБЫТКОВ.
#

#       Copyright (C) 2008-2012 Aleksandr Deviatkin, "Green Hill"
#
#       Redistribution and use in source and binary forms, with or without
#       modification, are permitted provided that the following conditions are
#       met:
#       
#       * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#       * Redistributions in binary form must reproduce the above
#         copyright notice, this list of conditions and the following disclaimer
#         in the documentation and/or other materials provided with the
#         distribution.
#       * Neither the name of the Green Hill nor the names of its
#         contributors may be used to endorse or promote products derived from
#         this software without specific prior written permission.
#       
#       THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#       "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#       LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#       A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#       OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#       SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#       LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#       DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#       THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#       (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#       OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


$|=1;
use DBI;
#use Time::Local;
use Date::Manip;
use strict;

#
# Расчёт потерь по всем балансным счётчикам по данным за сутки
# 2022-07-01 alid
#

my (@args, %opts);
foreach(@ARGV){
	if(/^\-(\S)(\S*)/) { $opts{$1} = $2; } else {  push @args, $_; }
}
my ($database, $date) = (@args);
die "Usage: $0 database [date]"		unless($database);
my $verb = exists $opts{v};
my $pgport = 5432;
my $pghost = 'localhost';

undef $date 	unless ($date =~ m/(\d{4})-(\d{2})-(\d{2})/);
unless ($date) {
	# Если не задана дата, то сегодня
#	$date = sprintf("%04d-%02d-%02d", sub{($_[5]+1900, $_[4]+1, $_[3])}->(localtime));
	$date =  UnixDate(ParseDate("today"), "%Y-%m-%d");
}


my $dbh = DBI->connect("dbi:Pg:dbname=$database;host=$pghost;port=$pgport","","", { RaiseError => 1, AutoCommit => 0});
my $sql = "
WITH
  dat AS (SELECT cast('$date' AS date) -1 AS dt),
  ordered AS (
  SELECT
    counter,
    se1ai AS se1,
    se2ai AS se2,
    date,
    first_value(se1ai) OVER (PARTITION BY counter ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS first_se1,
    last_value(se1ai) OVER (PARTITION BY counter ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_se1,
    first_value(se2ai) OVER (PARTITION BY counter ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS first_se2,
    last_value(se2ai) OVER (PARTITION BY counter ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_se2
  FROM ONLY monitor
  WHERE 
      the_date=(SELECT dt FROM dat)
    ),
  mains AS (
  SELECT DISTINCT
    counter,
    C.ktrans,
    G.id AS mgroup,
    (last_se1 - first_se1) * C.ktrans AS diff_se1,
    (last_se2 - first_se2) * C.ktrans AS diff_se2
  FROM ordered
    INNER JOIN counters C ON counter=C.id
      INNER JOIN mgroup G ON C.id=G.bid
  ORDER BY mgroup,counter
  ),
  lines AS (
  SELECT mgroup, sum(diff_se1) AS se1, sum(diff_se2) AS se2 FROM (
    SELECT DISTINCT
      counter,
      C.ktrans,
      C.mgroup AS mgroup,
      (last_se1 - first_se1) * C.ktrans AS diff_se1,
      (last_se2 - first_se2) * C.ktrans AS diff_se2
    FROM ordered
      INNER JOIN counters C ON counter=C.id
    ORDER BY mgroup,counter
    ) A
    GROUP BY mgroup
  )
INSERT INTO losses (the_date,mgroup,mgcounter_id,mg_se1,mg_se2,line_se1,line_se2,loss1,loss2,loss)
  SELECT
    (SELECT dt FROM dat),
    M.mgroup,
    M.counter AS mgcounter,
    M.diff_se1 AS gse1,
    M.diff_se2 AS gse2,
    L.se1 AS lse1,
    L.se2 AS lse2,
    (M.diff_se1-L.se1)/M.diff_se1 AS loos1,
    (M.diff_se2-L.se2)/M.diff_se2 AS loos2,
    ((M.diff_se1+M.diff_se2)-(L.se1+L.se2))/(M.diff_se1+M.diff_se2) AS loos
FROM mains M INNER JOIN lines L ON M.mgroup=L.mgroup;
";
$dbh->do($sql);

$dbh->commit;
$dbh->disconnect;
