#!/usr/local/bin/perl

#
#       Copyright (C) 2008-2012 Александр Девяткин, "Зелёная горка"
#
#       Разрешается повторное распространение и использование как в виде исходного
#       кода, так и в двоичной форме, с изменениями или без, при соблюдении следующих
#       условий:
#
#       * При повторном распространении исходного кода должно оставаться указанное
#         выше уведомление об авторском праве, этот список условий и последующий
#         отказ от гарантий.
#       * При повторном распространении двоичного кода должна сохраняться указанная
#         выше информация об авторском праве, этот список условий и последующий отказ
#         от гарантий в документации и/или в других материалах, поставляемых при
#         распространении.
#       * Ни название "Зелёная горка", ни имена ее сотрудников не могут быть
#         использованы в качестве поддержки или продвижения продуктов, основанных
#         на этом ПО без предварительного письменного разрешения.
#
#       ЭТА ПРОГРАММА ПРЕДОСТАВЛЕНА ВЛАДЕЛЬЦАМИ АВТОРСКИХ ПРАВ И/ИЛИ ДРУГИМИ СТОРОНАМИ
#	"КАК ОНА ЕСТЬ" БЕЗ КАКОГО-ЛИБО ВИДА ГАРАНТИЙ, ВЫРАЖЕННЫХ ЯВНО ИЛИ ПОДРАЗУМЕВАЕМЫХ,
#	ВКЛЮЧАЯ, НО НЕ ОГРАНИЧИВАЯСЬ ИМИ, ПОДРАЗУМЕВАЕМЫЕ ГАРАНТИИ КОММЕРЧЕСКОЙ ЦЕННОСТИ
#	И ПРИГОДНОСТИ ДЛЯ КОНКРЕТНОЙ ЦЕЛИ. НИ В КОЕМ СЛУЧАЕ, ЕСЛИ НЕ ТРЕБУЕТСЯ
#	СООТВЕТСТВУЮЩИМ ЗАКОНОМ, ИЛИ НЕ УСТАНОВЛЕНО В УСТНОЙ ФОРМЕ, НИ ОДИН ВЛАДЕЛЕЦ
#	АВТОРСКИХ ПРАВ И НИ ОДНО ДРУГОЕ ЛИЦО, КОТОРОЕ МОЖЕТ ИЗМЕНЯТЬ И/ИЛИ ПОВТОРНО
#	РАСПРОСТРАНЯТЬ ПРОГРАММУ, КАК БЫЛО СКАЗАНО ВЫШЕ, НЕ НЕСЁТ ОТВЕТСТВЕННОСТИ,
#	ВКЛЮЧАЯ ЛЮБЫЕ ОБЩИЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ ИЛИ ПОСЛЕДОВАВШИЕ УБЫТКИ,
#	ВСЛЕДСТВИЕ ИСПОЛЬЗОВАНИЯ ИЛИ НЕВОЗМОЖНОСТИ ИСПОЛЬЗОВАНИЯ ПРОГРАММЫ (ВКЛЮЧАЯ,
#	НО НЕ ОГРАНИЧИВАЯСЬ ПОТЕРЕЙ ДАННЫХ, ИЛИ ДАННЫМИ, СТАВШИМИ НЕПРАВИЛЬНЫМИ, ИЛИ
#	ПОТЕРЯМИ ПРИНЕСЕННЫМИ ИЗ-ЗА ВАС ИЛИ ТРЕТЬИХ ЛИЦ, ИЛИ ОТКАЗОМ ПРОГРАММЫ РАБОТАТЬ
#	СОВМЕСТНО С ДРУГИМИ ПРОГРАММАМИ), ДАЖЕ ЕСЛИ ТАКОЙ ВЛАДЕЛЕЦ ИЛИ ДРУГОЕ ЛИЦО БЫЛИ
#	ИЗВЕЩЕНЫ О ВОЗМОЖНОСТИ ТАКИХ УБЫТКОВ.
#

#       Copyright (C) 2008-2012 Aleksandr Deviatkin, "Green Hill"
#
#       Redistribution and use in source and binary forms, with or without
#       modification, are permitted provided that the following conditions are
#       met:
#       
#       * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#       * Redistributions in binary form must reproduce the above
#         copyright notice, this list of conditions and the following disclaimer
#         in the documentation and/or other materials provided with the
#         distribution.
#       * Neither the name of the Green Hill nor the names of its
#         contributors may be used to endorse or promote products derived from
#         this software without specific prior written permission.
#       
#       THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#       "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#       LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#       A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#       OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#       SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#       LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#       DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#       THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#       (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#       OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


$|=1;
use DBI;
use Time::Local;
use utf8;
use open qw(:std :utf8);
use strict;
use lib "$ENV{MY}/lib/";
#use GHPowerUtils;
use GHPower;
use XML::Simple;
use Date::Manip;

#
# Полный список счетчиков с показаниями на заданную дату
# 2018-08-12 alid
#

my (@args, %opts);
foreach(@ARGV){
	if(/^\-(\S)(\S*)/) { $opts{$1} = $2; } else {  push @args, $_; }
}
my ($date) = (@args);
$date =~ s/\s.*$//;
$date = UnixDate("yesterday","%Y-%m-%d")	unless($date);
die "Usage: $0 YYYY-MM-DD"	unless($date);

my $pgport = 5432;
my $database = $opts{D} || 'ghpower';

my $dbh = DBI->connect("dbi:Pg:dbname=$database;port=$pgport","","", { RaiseError => 1, AutoCommit => 1});
#my $sth = $dbh->prepare("SELECT C.id,C.mgroup,C.sn,C.dn,substring(C.dn from ',ou=(.+)\$') as street,substring(C.dn from 'ou=(.+),') as house,D.se1,D.se2,D.mode FROM counters C INNER JOIN daily D ON C.id=D.cid WHERE C.dn<>'' AND C.active=1 AND D.date=? order by street,house");
my $sth = $dbh->prepare("SELECT C.id,C.mgroup,C.sn,C.dn,S.name as street,P.number as house,D.se1,D.se2,D.mode FROM counters C INNER JOIN daily D ON C.id=D.cid INNER JOIN parcels P ON C.parcel_id=P.id INNER JOIN street S ON P.street_id=S.id WHERE C.parcel_id>0 AND C.active=1 AND D.date=? order by street,house");
#my $ghpower = GHPower->new($dbh);
#my $List = $ghpower->Domains_Struct;

my $XML = '<?xml version="1.0" encoding="UTF-8"?>'."\n";
$XML .= "<document>\n";
$XML .= "<header>Показания счетчиков на ".pdate()."</header>\n";
$XML .= "<fields>\n";
$XML .= "<field><name>street</name><order>1</order><label>Проезд</label><style>text-left</style></field>\n";
$XML .= "<field><name>number</name><order>2</order><label>Участок</label><style>text-center</style></field>\n";
$XML .= "<field><name>serial</name><order>3</order><label>Номер счётчика</label><style>text-right</style></field>\n";
$XML .= "<field><name>se1</name><order>4</order><label>Т1</label><style>text-right</style></field>\n";
$XML .= "<field><name>se2</name><order>5</order><label>Т1</label><style>text-right</style></field>\n";
$XML .= "</fields>\n";
$XML .= "<items>\n";

$sth->execute($date);
while(my $r = $sth->fetchrow_hashref) {
	next	if($r->{house} =~ m/^\D/);	# Номер должен начинаться с цифры
	$XML .= "<item>\n";
	$XML .= "<street>$r->{street}</street>\n";
	$XML .= "<number>$r->{house}</number>\n";
	$XML .= "<serial>".$r->{sn}."</serial>\n";
	if($r->{mode} eq '1') {	# однотарифная схема
		$XML .= "<se1>".($r->{se1} + $r->{se2})."</se1>\n";
		$XML .= "<se2></se2>\n";
	} else {
		$XML .= "<se1>".$r->{se1}."</se1>\n";
		$XML .= "<se2>".$r->{se2}."</se2>\n";
	}
	$XML .= "</item>\n";
}
$XML .= "</items>\n";
$XML .= "</document>\n";
$sth->finish;
$dbh->disconnect;
print $XML;

sub pdate {
	if($date =~ /(\d{4})\-(\d{2})\-(\d{2})/) {
		return sprintf("%02d.%02d.%d",$3,$2,$1);
	}
}


