#!/usr/bin/perl

#
#       Copyright (C) 2008-2012 áÌÅËÓÁÎÄÒ äÅ×ÑÔËÉÎ, "úÅÌ£ÎÁÑ ÇÏÒËÁ"
#
#       òÁÚÒÅÛÁÅÔÓÑ ÐÏ×ÔÏÒÎÏÅ ÒÁÓÐÒÏÓÔÒÁÎÅÎÉÅ É ÉÓÐÏÌØÚÏ×ÁÎÉÅ ËÁË × ×ÉÄÅ ÉÓÈÏÄÎÏÇÏ
#       ËÏÄÁ, ÔÁË É × Ä×ÏÉÞÎÏÊ ÆÏÒÍÅ, Ó ÉÚÍÅÎÅÎÉÑÍÉ ÉÌÉ ÂÅÚ, ÐÒÉ ÓÏÂÌÀÄÅÎÉÉ ÓÌÅÄÕÀÝÉÈ
#       ÕÓÌÏ×ÉÊ:
#
#       * ðÒÉ ÐÏ×ÔÏÒÎÏÍ ÒÁÓÐÒÏÓÔÒÁÎÅÎÉÉ ÉÓÈÏÄÎÏÇÏ ËÏÄÁ ÄÏÌÖÎÏ ÏÓÔÁ×ÁÔØÓÑ ÕËÁÚÁÎÎÏÅ
#         ×ÙÛÅ Õ×ÅÄÏÍÌÅÎÉÅ ÏÂ Á×ÔÏÒÓËÏÍ ÐÒÁ×Å, ÜÔÏÔ ÓÐÉÓÏË ÕÓÌÏ×ÉÊ É ÐÏÓÌÅÄÕÀÝÉÊ
#         ÏÔËÁÚ ÏÔ ÇÁÒÁÎÔÉÊ.
#       * ðÒÉ ÐÏ×ÔÏÒÎÏÍ ÒÁÓÐÒÏÓÔÒÁÎÅÎÉÉ Ä×ÏÉÞÎÏÇÏ ËÏÄÁ ÄÏÌÖÎÁ ÓÏÈÒÁÎÑÔØÓÑ ÕËÁÚÁÎÎÁÑ
#         ×ÙÛÅ ÉÎÆÏÒÍÁÃÉÑ ÏÂ Á×ÔÏÒÓËÏÍ ÐÒÁ×Å, ÜÔÏÔ ÓÐÉÓÏË ÕÓÌÏ×ÉÊ É ÐÏÓÌÅÄÕÀÝÉÊ ÏÔËÁÚ
#         ÏÔ ÇÁÒÁÎÔÉÊ × ÄÏËÕÍÅÎÔÁÃÉÉ É/ÉÌÉ × ÄÒÕÇÉÈ ÍÁÔÅÒÉÁÌÁÈ, ÐÏÓÔÁ×ÌÑÅÍÙÈ ÐÒÉ
#         ÒÁÓÐÒÏÓÔÒÁÎÅÎÉÉ.
#       * îÉ ÎÁÚ×ÁÎÉÅ "úÅÌ£ÎÁÑ ÇÏÒËÁ", ÎÉ ÉÍÅÎÁ ÅÅ ÓÏÔÒÕÄÎÉËÏ× ÎÅ ÍÏÇÕÔ ÂÙÔØ
#         ÉÓÐÏÌØÚÏ×ÁÎÙ × ËÁÞÅÓÔ×Å ÐÏÄÄÅÒÖËÉ ÉÌÉ ÐÒÏÄ×ÉÖÅÎÉÑ ÐÒÏÄÕËÔÏ×, ÏÓÎÏ×ÁÎÎÙÈ
#         ÎÁ ÜÔÏÍ ðï ÂÅÚ ÐÒÅÄ×ÁÒÉÔÅÌØÎÏÇÏ ÐÉÓØÍÅÎÎÏÇÏ ÒÁÚÒÅÛÅÎÉÑ.
#
#       üôá ðòïçòáííá ðòåäïóôá÷ìåîá ÷ìáäåìøãáíé á÷ôïòóëéè ðòá÷ é/éìé äòõçéíé óôïòïîáíé
#	"ëáë ïîá åóôø" âåú ëáëïçï-ìéâï ÷éäá çáòáîôéê, ÷ùòáöåîîùè ñ÷îï éìé ðïäòáúõíå÷áåíùè,
#	÷ëìàþáñ, îï îå ïçòáîéþé÷áñóø éíé, ðïäòáúõíå÷áåíùå çáòáîôéé ëïííåòþåóëïê ãåîîïóôé
#	é ðòéçïäîïóôé äìñ ëïîëòåôîïê ãåìé. îé ÷ ëïåí óìõþáå, åóìé îå ôòåâõåôóñ
#	óïïô÷åôóô÷õàýéí úáëïîïí, éìé îå õóôáîï÷ìåîï ÷ õóôîïê æïòíå, îé ïäéî ÷ìáäåìåã
#	á÷ôïòóëéè ðòá÷ é îé ïäîï äòõçïå ìéãï, ëïôïòïå íïöåô éúíåîñôø é/éìé ðï÷ôïòîï
#	òáóðòïóôòáîñôø ðòïçòáííõ, ëáë âùìï óëáúáîï ÷ùûå, îå îåó³ô ïô÷åôóô÷åîîïóôé,
#	÷ëìàþáñ ìàâùå ïâýéå, óìõþáêîùå, óðåãéáìøîùå éìé ðïóìåäï÷á÷ûéå õâùôëé,
#	÷óìåäóô÷éå éóðïìøúï÷áîéñ éìé îå÷ïúíïöîïóôé éóðïìøúï÷áîéñ ðòïçòáííù (÷ëìàþáñ,
#	îï îå ïçòáîéþé÷áñóø ðïôåòåê äáîîùè, éìé äáîîùíé, óôá÷ûéíé îåðòá÷éìøîùíé, éìé
#	ðïôåòñíé ðòéîåóåîîùíé éú-úá ÷áó éìé ôòåôøéè ìéã, éìé ïôëáúïí ðòïçòáííù òáâïôáôø
#	óï÷íåóôîï ó äòõçéíé ðòïçòáííáíé), äáöå åóìé ôáëïê ÷ìáäåìåã éìé äòõçïå ìéãï âùìé
#	éú÷åýåîù ï ÷ïúíïöîïóôé ôáëéè õâùôëï÷.
#

#       Copyright (C) 2008-2012 Aleksandr Deviatkin, "Green Hill"
#
#       Redistribution and use in source and binary forms, with or without
#       modification, are permitted provided that the following conditions are
#       met:
#       
#       * Redistributions of source code must retain the above copyright
#         notice, this list of conditions and the following disclaimer.
#       * Redistributions in binary form must reproduce the above
#         copyright notice, this list of conditions and the following disclaimer
#         in the documentation and/or other materials provided with the
#         distribution.
#       * Neither the name of the Green Hill nor the names of its
#         contributors may be used to endorse or promote products derived from
#         this software without specific prior written permission.
#       
#       THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#       "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#       LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#       A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#       OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#       SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#       LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#       DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#       THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#       (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#       OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


$|=1;
use DBI;
use Date::Manip;
use strict;

#
# åÖÅÍÅÓÑÞÎÏÅ ÏÂÎÏ×ÌÅÎÉÅ ÔÁÂÌÉÃÙ ÒÁÓÈÏÄÏ× ÐÏ ÓÞÅÔÞÉËÁÍ
# 2014-05-06 alid
#

my (@args, %opts);
foreach(@ARGV){
	if(/^\-(\S)(\S*)/) { $opts{$1} = $2; } else {  push @args, $_; }
}
my ($database) = (@args);
die "Usage: $0 database"		unless($database);
my $verb = exists $opts{v};
my $full = exists $opts{f};	# ÐÏÌÎÏÅ ÏÂÎÏ×ÌÅÎÉÅ ÔÁÂÌÉÃÙ
my $pgport = 5432;

my $dbh = DBI->connect("dbi:Pg:dbname=$database;port=$pgport","","", { RaiseError => 1, AutoCommit => 0});
my $sth = $dbh->prepare("SELECT id FROM counters");
my $sel = $dbh->prepare("SELECT id,(SELECT COUNT(*) FROM mexpenses WHERE cid=? AND year=? AND month=?) FROM mexpenses WHERE cid=? AND year=? AND month=?");
my $upd = $dbh->prepare("UPDATE mexpenses SET exp1=?,exp2=?,modtime=now() WHERE id=?");
my $ins = $dbh->prepare("INSERT INTO mexpenses (cid,year,month,exp1,exp2) VALUES (?,?,?,?,?)");
my $del = $dbh->prepare("DELETE FROM mexpenses WHERE cid=? AND year=? AND month=?");

# óÐÉÓÏË ÓÞÅÔÞÉËÏ×
my @List;
$sth->execute();
while(my ($r) = $sth->fetchrow_array) { push @List,$r;} $sth->finish;

if($full) {	# ÐÏÌÎÏÅ ÏÂÎÏ×ÌÅÎÉÅ
	$sth = $dbh->prepare("SELECT dt,se1ai,se2ai FROM monitor WHERE counter=? AND dt LIKE '%-01 %' ORDER BY dt DESC");
	print "Full update\n"	if $verb;
} else {	# ÔÏÌØËÏ ÐÏÓÌÅÄÎÉÊ ÍÅÓÑÃ
	# FreeBSD only:
	#my $lm = `date -v-1m "+%Y-%m"`; chomp $lm;

	my $edate = UnixDate("today","%Y-%m");
	my $sdate = UnixDate("1 month ago","%Y-%m");
	$sth = $dbh->prepare("SELECT dt,se1ai,se2ai FROM monitor WHERE counter=? AND ((dt>'$sdate-01 00:00:00' AND dt<'$sdate-01 23:59:59') OR (dt>'$edate-01 00:00:00' AND dt<'$edate-01 23:59:59')) ORDER BY dt DESC");
	print "Last month: $sdate - $edate\n"	if $verb;
}

foreach my $cid (@List) {
	print "cid=$cid\n"	if $verb;
	$sth->execute($cid);
	my $Data;
	while(my $r = $sth->fetchrow_hashref) {
		my ($year, $mon) = ($r->{dt} =~ m/^(\d{4})\-(\d{2})/);
		$Data->{$year}->{$mon} = $r;
	}
	$sth->finish;

	my ($data1,$data2);
	foreach my $year (sort {$b<=>$a} keys %$Data) {
		foreach my $mon (sort {$b<=>$a} keys %{$Data->{$year}}) {
			if(defined $data1) {
				print "$year $mon ".($data1 - $Data->{$year}->{$mon}->{se1ai})." ".($data2 - $Data->{$year}->{$mon}->{se2ai})."\n"	if $verb;
				setdata($cid,$year,$mon,$data1 - $Data->{$year}->{$mon}->{se1ai},$data2 - $Data->{$year}->{$mon}->{se2ai});
			}
			($data1,$data2) = ($Data->{$year}->{$mon}->{se1ai},$Data->{$year}->{$mon}->{se2ai});
		}
	}
#last;
}
$dbh->commit;
$dbh->disconnect;

sub setdata {
	my ($cid,$year,$month,$exp1,$exp2) = @_;
	$sel->execute($cid,$year,$month,$cid,$year,$month);
	my ($id,$count) = ($sel->fetchrow_array);
	$sel->finish;
	if($id && $count == 1) {
		$upd->execute($exp1,$exp2,$id);
	} else {
		$del->execute($cid,$year,$month)	if($count > 1);
		$ins->execute($cid,$year,$month,$exp1,$exp2);
	}
}


